name: Test

on:
  push:
    branches:
      - "main"
    paths:
      - "src/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/test.yml"
      - ".github/actions/rust-test/**"
  pull_request:
    branches:
      - "main"

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: true
  RUSTC_WRAPPER: sccache

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Test github-latest-release-downloader
        uses: ./.github/actions/rust-test
