name: Test

on:
  push:
    branches:
      - "main"
    paths:
      - "src/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/test.yml"
      - ".github/actions/rust-test/**"
  pull_request:
    branches:
      - "main"

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: true
  RUSTC_WRAPPER: sccache

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Test github-latest-release-downloader
        uses: ./.github/actions/rust-test
